<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="11.8.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\FIAP.AquaGuard.Exception\FIAP.AquaGuard.Exception.csproj" />
    <ProjectReference Include="..\FIAP.AquaGuard.Domain\FIAP.AquaGuard.Domain.csproj" />
    <ProjectReference Include="..\FIAP.AquaGuard.Infraestructure\FIAP.AquaGuard.Infrastructure.csproj" />
  </ItemGroup>

</Project>
